# Generated by Django 6.1.1 on 2026-09-30 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='ph-drop', help_text='Phosphor icon class name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('inquiry_type', models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Private Tasting', 'Private Tasting & Event'), ('Cellar Advisory', 'Cellar Advisory & Rare Spirits'), ('Wholesale', 'Wholesale & Hospitality')], default='General Inquiry', max_length=50)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=30)),
                ('shipping_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('delivery_notes', models.TextField(blank=True)),
                ('payment_method', models.CharField(default='Credit Card', max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon_code', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Preparing', 'Cellar Preparation'), ('Shipped', 'Dispatched for Courier Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Processing', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount if on sale', max_digits=10, null=True)),
                ('currency', models.CharField(default='$', max_length=10)),
                ('short_description', models.TextField(help_text='Short description shown in catalog cards')),
                ('full_description', models.TextField(blank=True, help_text='Detailed overview for product details')),
                ('image_url', models.URLField(help_text='Primary high-res image URL', max_length=800)),
                ('secondary_image_url', models.URLField(blank=True, help_text='Secondary tasting/bottle image', max_length=800)),
                ('badge', models.CharField(blank=True, choices=[('', 'None'), ('limited', 'Limited Edition'), ('new', 'New Arrival'), ('award', 'Award Winner'), ('sale', 'On Sale'), ('rare', 'Rare Cellar Find')], max_length=20)),
                ('badge_text', models.CharField(blank=True, help_text='Custom badge display text like "Limited", "97 pts", "Award Winner"', max_length=50)),
                ('abv', models.DecimalField(decimal_places=1, default=40.0, help_text='Alcohol by Volume (%)', max_digits=4)),
                ('volume', models.CharField(default='750ml', max_length=20)),
                ('age_years', models.PositiveIntegerField(blank=True, help_text='Cask aging in years (e.g., 12, 18, 25)', null=True)),
                ('origin', models.CharField(default='Highlands, Scotland', help_text='Region and Country of origin', max_length=150)),
                ('cask_type', models.CharField(blank=True, default='Charred American White Oak', help_text='Maturation cask type', max_length=150)),
                ('nose_notes', models.CharField(blank=True, default='Caramelized orange, vanilla bean, subtle oak smoke', help_text='Aromas on the nose', max_length=255)),
                ('palate_notes', models.CharField(blank=True, default='Rich toffee, dark cocoa, baked orchard fruit, gentle peat', help_text='Flavors on the palate', max_length=255)),
                ('finish_notes', models.CharField(blank=True, default='Long, warming spice with lingering honeyed tobacco', help_text='Finish characteristics', max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=12)),
                ('stock', models.PositiveIntegerField(default=25)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in Curated Selection on Home Page')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.URLField(blank=True, max_length=800)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('comment', models.TextField()),
                ('is_verified_buyer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
