# Generated by Django 6.1.1 on 2026-10-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cask_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='₦', max_length=10),
        ),
    ]
