# Generated by Django 6.1.1 on 2026-10-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_cask_type_alter_product_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Admin-issued VIP voucher code', max_length=50, unique=True)),
                ('discount_percent', models.PositiveSmallIntegerField(choices=[(10, '10% Discount'), (20, '20% Discount'), (50, '50% Discount')], default=10, help_text='Discount percentage (limited strictly to 10%, 20%, or 50%)')),
                ('recipient_email', models.EmailField(blank=True, help_text='Email of the user this voucher is generated for and sent to', max_length=254)),
                ('recipient_name', models.CharField(blank=True, help_text='Optional recipient name', max_length=120)),
                ('description', models.CharField(blank=True, help_text='Internal notes or reason for issuing', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this coupon can currently be redeemed')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Maximum number of times this code can be redeemed (0 for unlimited)')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Number of times redeemed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
